apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: docker-k8s-test
  name: docker-k8s-test
spec:
  replicas: 2
  selector:
    matchLabels:
      run: docker-k8s-test
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: docker-k8s-test
    spec:
      containers:
      - image: briandemant/docker-k8s-test:1.0
        imagePullPolicy: Always
        name: docker-k8s-test
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: docker-k8s-test
spec:
  type: NodePort
  selector:
    app: docker-k8s-test
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: docker-k8s-test
spec:
  rules:
    - host: lab.18.220.58.120.xip.io
      http:
        paths:
          - path: /
            backend:
              serviceName: intro-app
              servicePort: 80
